# Generated by Django 4.2.7 on 2023-12-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aircraft_Model', models.CharField(max_length=50)),
                ('Serialnumber', models.CharField(max_length=50, unique=True)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airport_Name', models.CharField(max_length=200, unique=True)),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('ICAO_Code', models.CharField(max_length=4, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_Id', models.CharField(max_length=200, unique=True)),
                ('Flight_name', models.CharField(max_length=200, unique=True)),
                ('Flight_from', models.CharField(max_length=200)),
                ('Flight_to', models.CharField(max_length=200)),
                ('Departure_Datetime', models.DateTimeField()),
                ('Arrival_Datetime', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='app_flight.airport')),
                ('Departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='app_flight.airport')),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_flight.aircraft')),
            ],
        ),
    ]
