# Generated by Django 4.2.7 on 2023-12-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='Flight_from',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='Flight_to',
        ),
    ]
